---
title: "integration"
author: "Siwanart Ma"
date: "2025-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Seurat)
library(tidyverse)
```

```{r}
mem.maxVSize(vsize = 80000)
# Load 4-6 weeks Seurat object
load("/Users/mayongzhi/Desktop/researchProject/integration/originals/human4_6W.RData")

# Load 7-11 weeks Seurat object
load("/Users/mayongzhi/Desktop/researchProject/integration/originals/human7_11W.RData")
human7_11W <- seurat
rm(seurat)

# Load 12-20 weeks Seurat object
load("/Users/mayongzhi/Desktop/researchProject/integration/originals/human12_20W.RData")
human12_20W <- humanpancreas.combined.sct
rm(humanpancreas.combined.sct)
```


```{r}
merged_object <- readRDS("../outputs/merged_object.rds")
merged_object
```


```{r}
library(future)
library(Seurat)
library(ggplot2)
library(patchwork)
options(future.globals.maxSize = 1e9)

mem.maxVSize(vsize = 100000)
gc()

separate.list <- c(human4_6W, human7_11W, human12_20W)

features <- SelectIntegrationFeatures(
  separate.list, nfeatures = 3000,
  verbose = TRUE)

VariableFeatures(merged_object) <- features

merged_object <- RunPCA(merged_object, features = VariableFeatures(merged_object))
saveRDS(merged_object, "../outputs/merged_object_pca.rds")
integrated <- IntegrateLayers(
  object = merged_object, method = CCAIntegration,
  normalization.method = "SCT",
  new.reduction = "integrated.pca",
  verbose = FALSE
)
```

